server:
  port: 8080
  servlet:
    context-path: /girl
selfParam: A
age: 18
content: "selfParam:${selfParam},age:${age}"
boy:
  name: "张三"
  emial: "1231233@qq.com"
  height: 175
  weight: 120
  habit:
      - 篮球
      - 足球
spring:
  profiles:
    active: @profileActive@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    maxActive: 20
    minIdle: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # poolPreparedStatements: Oracle为true，MySql可为false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    filters: stat,log4j

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform:
    open-in-view: true
  #指定静态资源加载位置 pring.resources.static-locations 的默认值是：classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
---
spring:
  profiles: dev
  datasource:
    testdb:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
    demodb:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
