server:
  port: 8089
  servlet:
    context-path: /girl
selfParam: A
age: 18
content: "selfParam:${selfParam},age:${age}"
boy:
  name: "张三"
  emial: "1231233@qq.com"
  height: 175
  weight: 120
  habit:
      - 篮球
      - 足球
netty:
  port: 8888    #监听端口
  bossThread: 2 #线程数
  workerThread: 2 #线程数
  keepalive: true #保持连接
  backlog: 100
spring:
  profiles:
    active: @profileActive@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    maxActive: 20
    minIdle: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # poolPreparedStatements: Oracle为true，MySql可为false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    filters: stat,log4j
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform:
    open-in-view: true
  #指定静态资源加载位置 pring.resources.static-locations 的默认值是：classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  redis:
    host: 192.168.217.130
    password: 123456
    port: 6379
    timeout: 1000
    database: 0
    pool:
      #最大连接数据库连接数,设 0 为没有限制
      max-active: 8
          #最大等待连接中的数量,设 0 为没有限制
      max-idle: 10
          #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
      max-wait: -1
          #最小等待连接中的数量,设 0 为没有限制
      min-idle: 0
  rabbitmq:
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    host: 192.168.217.130
    port: 5672

  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

http:
  #最大连接数
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true

sftp:
  host: 10.226.50.5  # 服务器ip
  port: 22 # ssh端口
  username: root # 用户名
  password: Golic118 # 密码
  # 连接池参数
  pool:
    max-total: 10
    max-idle: 10
    min-idle: 5

---
spring:
  profiles: dev
  datasource:
    testdb:
       driverClassName: oracle.jdbc.driver.OracleDriver  # oracle驱动
       url: jdbc:oracle:thin:@10.226.95.174:1521:SCPDCP
       username: FAW_TEST
       password: FAW_TEST
    demodb:
      driverClassName: oracle.jdbc.driver.OracleDriver  # oracle驱动
      url: jdbc:oracle:thin:@10.226.95.174:1521:SCPDCP
      username: FAW_TEST
      password: FAW_TEST
   # testdb:
   #   driverClassName: com.mysql.jdbc.Driver
   #   url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
   #   username: root
   #   password: 123456
   # demodb:
   #   driverClassName: com.mysql.jdbc.Driver
   #   url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
   #   username: root
   #   password: 123456
